extra-files:
  - ./lib1.so
  - ./lib2.so
pdfs:
#  # Example 1:
  - gaussian
  - double_gaussian
#  # Example 2:
#  - gaussian
#  - double_gaussian
#  # Example 3:
#  - gaussian
#  - double_gaussian
#  - test_func
#  # Example 4:
#  - gaussian
#  - test_func
